---
# Variable OS Family specific.
- name: Include OS Family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - os_family

# Variable OS version specific.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'
  tags:
    - os_debian_variables

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'
  - ansible_distribution != 'Amazon'
  tags:
    - os_rhel_variables

- name: Include OS-specific variables (Rocky).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'Rocky'
  - ansible_distribution != 'Fedora'
  - ansible_distribution != 'Amazon'
  tags:
    -  os_rocky_variables

- name: Include OS-specific variables (Amazon).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Amazon'
  tags:
    -  os_amazon_variables

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'
  tags:
    -  os_fedora_variables