---
# Variable OS Family specific.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Variable OS version specific.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'
  - ansible_distribution != 'Amazon'

- name: Include OS-specific variables (Rocky).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'Rocky'
  - ansible_distribution != 'Fedora'
  - ansible_distribution != 'Amazon'

- name: Include OS-specific variables (Amazon).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Amazon'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

# Run tasks.
- name: Deploy common role on RHEL Familly
  import_tasks: rhel-main.yml
  when: ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  tags:
    - os-commons-rhel

- name: Deploy common role on Debian Familly
  import_tasks: debian-main.yml
  when: (ansible_facts['os_family'] == "Debian")
  tags:
    - os-common-debian