---
# Loading OS correct vars
- name: Loading OS correct vars
  include_tasks: load_vars.yml
  tags:
    - load_vars
    
# Run tasks.
- name: Deploy common role on RHEL Familly
  import_tasks: rhel-main.yml
  when: ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  tags:
    - main-rhel

- name: Deploy common role on Debian Familly
  import_tasks: debian-main.yml
  when: (ansible_facts['os_family'] == "Debian")
  tags:
    - main-debian